### ISSUE TITLE
Make BIP-322 Message Dynamic

### ISSUE THREAD

**Issue by captain-munch** [muncheruniverse/munch-cord#10]
For each verification process, we should have a dynamic `message` which is specific to the user's verify session. 

Currently this is static for testing via `const BIP_MESSAGE = 'munch munch'`

**Comment by rk1129** [comment]
![image](https://user-images.githubusercontent.com/122992252/228595370-d75abe10-9fef-4db4-8a50-c94c51a96ad3.png)
Completed it

**Comment by rk1129** [comment]
![image](https://user-images.githubusercontent.com/122992252/228615910-1b67afe9-b90d-4964-9da7-e2d79a772e01.png)

Complete this by creating a new table

**Comment by captain-munch** [comment]
this was sorted
