### ISSUE TITLE
Add marketplace ingest

### ISSUE THREAD

**Issue by captain-munch** [muncheruniverse/munch-cord#26]
We should create a simply marketplace ingest, which will automate the creation of a collection. 

For example, instead of inscription ids being pasted manually, lets take a marketplace URL and paginate through their underlying API to fetch the inscription ids. 

https://magiceden.io/ordinals/marketplace/blockmunchers

this will fetch the underlying API:

https://api-mainnet.magiceden.io/v2/ord/btc/tokens?limit=20&offset=0&sortBy=priceAsc&minPrice=0&maxPrice=0&collectionSymbol=blockmunchers

and paginate it until it has grabbed all the inscription ids of the collection. 

In the code, this should be structured in such as way, that we will add other marketplaces, it would be nice to have 1 class per marketplace so they are easy to maintain/update etc.

For the command, lets call this `/collection-add-<marketplace>` so in this case, `/collection-add-magiceden` - at this stage i would rather be explicit about who we support.

**Comment by rk1129** [comment]
![image](https://user-images.githubusercontent.com/122992252/228941530-1738033d-634b-4546-9bce-6caa96a3394b.png)
Add collection-add-magiceden command

**Comment by captain-munch** [comment]
Theres a problem using the modal for larger collections such as degods because of timeout issues: 

<img width="485" alt="image" src="https://user-images.githubusercontent.com/127023971/228974859-fb707f36-19d8-4914-921d-96542947ad80.png">

I think we probably need to move to an inline prompt, it looks like this: 

<img width="389" alt="image" src="https://user-images.githubusercontent.com/127023971/228975105-f80670e7-06ca-46f4-89b1-5dce411b4d81.png">

So it can ask for the collection symbol and an optional collection name (if not set, then use the name from magic eden for the collection): 

<img width="248" alt="image" src="https://user-images.githubusercontent.com/127023971/228975213-1244c7db-9388-42ee-83cb-96d24fd9f554.png">

**Comment by rk1129** [comment]
![image](https://user-images.githubusercontent.com/122992252/229088381-6a78c5f3-a087-4d59-9fa8-65727d155b5d.png)

implement collection-marketplace command `rk#26/add-collection-marketplace-command`

**Comment by captain-munch** [comment]
Add refactor to create an interface for making adding new marketplaces nice and simple.

**Comment by rk1129** [comment]
![image](https://user-images.githubusercontent.com/122992252/229855665-8913270a-461d-4377-809a-551d61b17dd0.png)


Add gamma marketplace

**Comment by captain-munch** [comment]
this is sorted now
