### ISSUE TITLE
Switch to address lookup

### ISSUE THREAD

**Issue by captain-munch** [muncheruniverse/munch-cord#40]
In preparation for wallet integrations, we should accept the wallet address, instead of the inscription id. 

Once the wallet address has been verified via BIP-322 flow, we should iterate each inscription id held by that wallet and look for a match and allocate that role.

For now, we can use ordapi for this: `https://ordapi.xyz/address/bc1...`

**Comment by rk1129** [comment]
![image](https://user-images.githubusercontent.com/122992252/230318434-3aa9deb0-40b7-49e0-a5e1-c925ce34ab51.png)

Completed

**Comment by captain-munch** [comment]
this is sorted
