### ISSUE TITLE
Better Verify Success Output

### ISSUE THREAD

**Issue by captain-munch** [muncheruniverse/munch-cord#51]
When a user successfully verifies, we should confirm all of the roles and collections that they have matched against. 

Lets use the same format as the `/collection-view` output, but with the green success style: 

<img width="377" alt="image" src="https://user-images.githubusercontent.com/127023971/230368611-f48e6c29-7727-4e2a-9013-6c2f4cd77cb8.png">

On a Verify success, it should grab all the collection names and roles for the user id for that channel id, and display them in the same way as above (the inscription counts should show the number they have matched within each collection). 

This must be done via DB query, so that we can capture all collections, roles, and count across all the addresses they have verified with in the channel. 

It is worth also creating a userAddress table that captures each unique address that a user verifies with.

**Comment by rk1129** [comment]
![image](https://user-images.githubusercontent.com/122992252/230598405-59658f90-0b43-4d04-9aa5-48d94eb593fa.png)

Completed

**Comment by captain-munch** [comment]
this is awesome, tweaked with b3f046d0cacd413afc56203088fe0be0873da849
