### ISSUE TITLE
User Addresses

### ISSUE THREAD

**Issue by captain-munch** [muncheruniverse/munch-cord#59]
When a user verifies, we should capture their address into a new table, which will allow us to run better analysis and to re-scan addresses to ensure that each user still has the correct roles. 

For example:

Day 1: 

User verifies address bc1... and has 2 inscriptions and is allocated @Holder and @Muncher roles. 

Day 3: 

User sells their Muncher, but still has the @Muncher role. 

We should create a re-scan command that will allow a server owner to re-check all users to ensure they have the most up to date roles allocated.

**Comment by rk1129** [comment]
I added re-scan command
Please check on your side and give me some feedbacks, so I will fix it.

**Comment by captain-munch** [comment]
this is sorted
