### ISSUE TITLE
Pre-release

### ISSUE THREAD

**Issue by muncheruniverse** [muncheruniverse/munch-cord#9]
- [x] update all `const embed = errorEmbed('Error happened');` to use `rawError`
- [x] catch edge case where bot is attempted to be `/setup` in a private channel before its invited - it actually enables the channel but it cant create the Verify message
- [x] allow for local `.env.local` to be used
- [x] remove all duplicate `errorEmbed('You are not owner of this server or this channel is not registered for the bot.')` into a single include.

**Comment by rk1129** [comment]
Complete first task

https://github.com/muncheruniverse/munch-cord/tree/rk%239/update-all-embed-to-print-rawError

**Comment by rk1129** [comment]
Complete second task.
Allowed local env
https://github.com/muncheruniverse/munch-cord/tree/rk%239/allow-local-env

**Comment by rk1129** [comment]
Complete third task
https://github.com/muncheruniverse/munch-cord/tree/rk%239/catch-edge-case
